version: "3.9"

services:
  react-app:
    build: .
    ports:
      - "443:443"    # Проброс порта 8443
    volumes:
      - ./certs/cert.pem:/etc/nginx/certs/cert.pem  # SSL сертификат
      - ./certs/privkey.pem:/etc/nginx/certs/privkey.pem  # Приватный ключ
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Конфигурация Nginx
    restart: always
